(() => {
  const mount = document.querySelector('#adminManagement');
  if (!mount) return;
  let state = { shops: [], warehouses: [], shopWarehouses: [], users: [] };
  let activeTab = 'overview';
  const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]);
  const token = () => { try { return JSON.parse(localStorage.getItem('tiktokShopAuthSession') || sessionStorage.getItem('tiktokShopAuthSession') || '{}').accessToken; } catch { return null; } };
  async function api(url, options = {}) { const response = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token()}`, ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || '操作失败'); return data; }
  const shopChecks = (checked = []) => state.shops.map(shop => `<label><input type="checkbox" value="${shop.id}" ${checked.includes(shop.id) ? 'checked' : ''}/> ${escapeHtml(shop.shop_name)}</label>`).join('') || '<span class="admin-empty">请先新增店铺</span>';
  const warehouseChecks = (checked = []) => state.warehouses.filter(item => item.is_active).map(item => `<label><input type="checkbox" value="${item.id}" ${checked.includes(item.id) ? 'checked' : ''}/> ${escapeHtml(item.name)}</label>`).join('') || '<span class="admin-empty">暂未建立可用仓库</span>';
  const warehousesFor = shopId => state.shopWarehouses.filter(item => item.shop_id === shopId).map(item => item.warehouse_id);
  function overview() {
    const activeShops = state.shops.filter(shop => shop.is_active).length;
    const businessUsers = state.users.filter(user => user.roles.includes('business_user')).length;
    const unassigned = state.users.filter(user => user.roles.includes('business_user') && !user.shopIds.length).length;
    return `<section class="admin-section-heading"><div><p class="eyebrow">OVERVIEW</p><h3>管理工作概览</h3><p>基础资料、角色和店铺授权会成为业务端可读取的真实数据。</p></div></section><section class="admin-kpis"><article><span>启用店铺</span><strong>${activeShops}</strong><small>共 ${state.shops.length} 个店铺</small></article><article><span>已创建成员</span><strong>${state.users.length}</strong><small>${businessUsers} 名业务员</small></article><article><span>待补充授权</span><strong>${unassigned}</strong><small>业务员尚未分配店铺</small></article><article><span>可用仓库</span><strong>${state.warehouses.filter(item => item.is_active).length}</strong><small>用于店铺关联</small></article></section><section class="admin-card admin-next"><h4>当前第一阶段已覆盖</h4><p>管理员可以建立店铺、登记仓库、创建成员并授予店铺权限；业务员的“我的店铺”仅显示真实分配给自己的店铺。</p><button class="admin-tab-link" data-tab="shops">去配置店铺与仓库</button></section>`;
  }
  function shopsTab() {
    const rows = state.shops.map(shop => `<tr data-shop="${shop.id}"><td><strong>${escapeHtml(shop.shop_name)}</strong><br/><small>${escapeHtml(shop.shop_code)}</small></td><td>${escapeHtml(shop.country_code)} / ${escapeHtml(shop.currency_code)}</td><td><div class="admin-shop-list">${warehouseChecks(warehousesFor(shop.id))}</div></td><td><label class="admin-switch"><input class="shop-active" type="checkbox" ${shop.is_active ? 'checked' : ''}/><span>${shop.is_active ? '启用' : '停用'}</span></label></td><td><button class="admin-save" data-save-shop="${shop.id}">保存</button></td></tr>`).join('') || '<tr><td colspan="5" class="admin-empty">暂未建立店铺</td></tr>';
    const warehouseRows = state.warehouses.map(item => `<tr><td>${escapeHtml(item.name)}</td><td>${escapeHtml(item.country_code || '跨境')}</td><td>${item.is_active ? '可用' : '已停用'}</td></tr>`).join('') || '<tr><td colspan="3" class="admin-empty">暂未建立仓库</td></tr>';
    return `<section class="admin-section-heading"><div><p class="eyebrow">MASTER DATA</p><h3>店铺与仓库</h3><p>店铺是权限和利润核算的基础单位；每个店铺可关联一个或多个发货仓库。</p></div></section><section class="admin-card"><h4>新增店铺</h4><form id="createShopForm" class="admin-form"><label>店铺编码<input name="shopCode" required placeholder="例如 PH-001"/></label><label>店铺名称<input name="shopName" required placeholder="例如 PH 官方店"/></label><label>国家站点<input name="countryCode" required maxlength="2" placeholder="例如 PH"/></label><label>结算币种<input name="currencyCode" required maxlength="3" placeholder="例如 PHP"/></label><button>新增店铺</button></form></section><section class="admin-card"><h4>店铺配置</h4><p>保存后，已获授权成员的“我的店铺”会读取新的店铺状态与关联仓库。</p><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>店铺</th><th>站点 / 币种</th><th>关联仓库</th><th>状态</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></section><section class="admin-card"><h4>仓库目录</h4><p>首版仅新增仓库；停用、修改和成本维护将在成本模块上线时统一提供。</p><form id="createWarehouseForm" class="admin-form"><label>仓库名称<input name="name" required placeholder="例如 马来西亚本土"/></label><label>国家站点<input name="countryCode" maxlength="2" placeholder="例如 MY；跨境仓留空"/></label><button>新增仓库</button></form><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>仓库</th><th>所属站点</th><th>状态</th></tr></thead><tbody>${warehouseRows}</tbody></table></div></section>`;
  }
  function membersTab() {
    const users = state.users.map(user => `<tr data-user="${user.id}"><td><strong>${escapeHtml(user.displayName || '未设置姓名')}</strong><br/><small>${escapeHtml(user.email || '—')}</small></td><td>${user.confirmed ? '已激活' : '等待激活'}</td><td><select class="member-role"><option value="business_user" ${user.roles.includes('business_user') ? 'selected' : ''}>业务员</option><option value="finance" ${user.roles.includes('finance') ? 'selected' : ''}>财务</option><option value="admin" ${user.roles.includes('admin') ? 'selected' : ''}>管理员</option><option value="super_admin" ${user.roles.includes('super_admin') ? 'selected' : ''}>超级管理员</option></select></td><td><div class="admin-shop-list">${shopChecks(user.shopIds)}</div></td><td><button class="admin-save" data-save-user="${user.id}">保存权限</button>${!user.confirmed ? `<button class="admin-delete" data-delete-pending="${user.id}">删除未激活账号</button>` : ''}</td></tr>`).join('') || '<tr><td colspan="5" class="admin-empty">暂未创建成员</td></tr>';
    return `<section class="admin-section-heading"><div><p class="eyebrow">ACCESS CONTROL</p><h3>成员与店铺权限</h3><p>业务员只能查看被勾选的店铺；财务和管理员拥有更高的数据管理权限。</p></div></section><section class="admin-card"><h4>创建成员账号</h4><p>管理员填写邮箱、角色、可访问店铺和初始密码，再通过公司内部方式发送给业务员。</p><form id="inviteMemberForm" class="admin-form"><label>成员邮箱<input name="email" type="email" required placeholder="member@example.com"/></label><label>初始密码<input name="password" type="password" required minlength="8" placeholder="至少 8 位"/></label><label>初始角色<select name="role"><option value="business_user">业务员</option><option value="finance">财务</option><option value="admin">管理员</option></select></label><div class="admin-shop-list admin-form-checks">${shopChecks()}</div><button>创建成员账号</button></form></section><section class="admin-card"><h4>成员列表与授权</h4><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>成员</th><th>状态</th><th>角色</th><th>可查看店铺</th><th></th></tr></thead><tbody>${users}</tbody></table></div></section>`;
  }
  function render(message = '') {
    const content = activeTab === 'shops' ? shopsTab() : activeTab === 'members' ? membersTab() : overview();
    mount.innerHTML = `<nav class="admin-module-nav"><button data-tab="overview" class="${activeTab === 'overview' ? 'active' : ''}">概览</button><button data-tab="shops" class="${activeTab === 'shops' ? 'active' : ''}">店铺与仓库</button><button data-tab="members" class="${activeTab === 'members' ? 'active' : ''}">成员与权限</button><button disabled>商品审核（下一阶段）</button><button disabled>成本与汇率（下一阶段）</button><button disabled>数据导入（下一阶段）</button></nav>${message ? `<p class="admin-message">${message}</p>` : ''}${content}`;
    mount.querySelectorAll('[data-tab]').forEach(button => button.addEventListener('click', () => { activeTab = button.dataset.tab; render(); }));
    mount.querySelector('#createShopForm')?.addEventListener('submit', createShop); mount.querySelector('#createWarehouseForm')?.addEventListener('submit', createWarehouse); mount.querySelector('#inviteMemberForm')?.addEventListener('submit', inviteMember);
    mount.querySelectorAll('[data-save-shop]').forEach(button => button.addEventListener('click', saveShop)); mount.querySelectorAll('[data-save-user]').forEach(button => button.addEventListener('click', saveAccess)); mount.querySelectorAll('[data-delete-pending]').forEach(button => button.addEventListener('click', deletePending));
  }
  async function load(message = '') { state = await api('/api/admin/data'); render(message); }
  async function execute(task, success) { try { await task(); await load(success); } catch (error) { render(`<span class="admin-error">${escapeHtml(error.message)}</span>`); } }
  async function createShop(event) { event.preventDefault(); const form = new FormData(event.currentTarget); await execute(() => api('/api/admin/shops', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }), '店铺已新增。请在下方关联仓库后保存。'); }
  async function createWarehouse(event) { event.preventDefault(); const form = new FormData(event.currentTarget); await execute(() => api('/api/admin/warehouses', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }), '仓库已新增。'); }
  async function saveShop(event) { const row = event.currentTarget.closest('tr'); await execute(() => api('/api/admin/shops/configuration', { method: 'PUT', body: JSON.stringify({ shopId: row.dataset.shop, isActive: row.querySelector('.shop-active').checked, warehouseIds: [...row.querySelectorAll('.admin-shop-list input:checked')].map(input => input.value) }) }), '店铺配置已保存，业务端会读取最新资料。'); }
  async function inviteMember(event) { event.preventDefault(); const form = event.currentTarget; await execute(() => api('/api/admin/members', { method: 'POST', body: JSON.stringify({ email: form.email.value, password: form.password.value, role: form.role.value, shopIds: [...form.querySelectorAll('input[type=checkbox]:checked')].map(input => input.value) }) }), '成员账号已创建，请通过公司内部方式发送初始密码。'); }
  async function saveAccess(event) { const row = event.currentTarget.closest('tr'); await execute(() => api('/api/admin/members/access', { method: 'PUT', body: JSON.stringify({ userId: row.dataset.user, role: row.querySelector('.member-role').value, shopIds: [...row.querySelectorAll('.admin-shop-list input:checked')].map(input => input.value) }) }), '成员权限已保存，业务端权限即时生效。'); }
  async function deletePending(event) { const userId = event.currentTarget.dataset.deletePending; if (!window.confirm('确认删除这个未激活邀请账号？删除后无法恢复。')) return; await execute(() => api('/api/admin/members/pending', { method: 'DELETE', body: JSON.stringify({ userId }) }), '未激活邀请账号已删除。'); }
  document.addEventListener('app:authenticated', event => { if (['admin', 'super_admin'].includes(event.detail.role)) load().catch(error => render(`<span class="admin-error">${escapeHtml(error.message)}</span>`)); });
})();
