(() => {
  const dialog=document.querySelector('#generalFeedbackDialog'),pageInput=document.querySelector('#generalFeedbackPage'),content=document.querySelector('#generalFeedbackContent'),result=document.querySelector('#generalFeedbackResult');
  const pageNames={dashboard:'首页（数据看板）',currencyPage:'汇率中心',productsPage:'商品管理',shippingPage:'运费管理',ordersPage:'订单管理',storesPage:'我的店铺',summaryPage:'利润汇总'};
  const currentPage=()=>Object.entries(pageNames).find(([id])=>!document.querySelector(`#${id}`)?.classList.contains('is-hidden'))?.[1]||'当前页面';
  document.querySelector('.feedback-button')?.addEventListener('click',()=>{pageInput.value=currentPage();content.value='';document.querySelector('#generalFeedbackImage').value='';result.textContent='';dialog.showModal();});
  document.querySelector('#closeGeneralFeedback')?.addEventListener('click',()=>dialog.close());
  document.querySelector('#submitGeneralFeedback')?.addEventListener('click',()=>{const text=content.value.trim();if(!text){result.textContent='请填写具体反馈内容后再提交。';return;}const key='tiktokShopGeneralFeedbacks',items=JSON.parse(localStorage.getItem(key)||'[]'),id=`FB-${Date.now().toString().slice(-8)}`;items.unshift({id,type:document.querySelector('#generalFeedbackType').value,page:pageInput.value,content:text,createdAt:new Date().toLocaleString('zh-CN',{hour12:false}),status:'待处理'});localStorage.setItem(key,JSON.stringify(items));result.textContent=`反馈已提交，编号：${id}，管理员将尽快处理。`;});
  const historyButton=document.createElement('button');historyButton.type='button';historyButton.className='feedback-history-trigger';historyButton.textContent='反馈历史';dialog.querySelector('h2')?.after(historyButton);
  const historyDialog=document.createElement('dialog');historyDialog.className='feedback-dialog feedback-history-dialog';historyDialog.innerHTML='<button class="dialog-close" type="button" aria-label="关闭">×</button><h2>反馈历史</h2><div class="history-tabs"><button class="active" data-history-tab="general" type="button">意见反馈</button><button data-history-tab="product" type="button">商品管理反馈</button></div><div class="feedback-history-list"></div>';document.body.append(historyDialog);
  const general=()=>JSON.parse(localStorage.getItem('tiktokShopGeneralFeedbacks')||'[]').map(x=>({id:x.id,type:x.type,context:x.page,time:x.createdAt,content:x.content,status:x.status}));
  const products=()=>JSON.parse(localStorage.getItem('tiktokShopProductFeedbacks')||'[]').map(x=>({id:x.id,type:x.issue,context:`${x.sku} · ${x.name||'商品信息'}`,time:x.submittedAt,content:x.content,status:x.status,warehouse:x.warehouse}));
  function renderHistory(tab='general'){const list=historyDialog.querySelector('.feedback-history-list'),items=tab==='product'?products():general();list.innerHTML=items.length?items.map((x,i)=>`<article class="history-entry"><button class="history-summary" type="button" data-history-entry="${i}"><span><b>${x.id}</b><small>${x.type} · ${x.context} · ${x.time}</small></span><em class="feedback-status">${x.status}</em><i>⌄</i></button><div class="history-expanded is-hidden"><p>${x.content}</p>${x.warehouse?`<small>关联仓库：${x.warehouse}</small>`:''}<small>管理员处理说明：等待管理员处理</small></div></article>`).join(''):'<div class="feedback-empty">暂无历史反馈</div>';}
  historyButton.addEventListener('click',()=>{historyDialog.querySelectorAll('[data-history-tab]').forEach(b=>b.classList.toggle('active',b.dataset.historyTab==='general'));renderHistory();historyDialog.showModal();});
  historyDialog.querySelectorAll('[data-history-tab]').forEach(button=>button.addEventListener('click',()=>{historyDialog.querySelectorAll('[data-history-tab]').forEach(b=>b.classList.toggle('active',b===button));renderHistory(button.dataset.historyTab);}));
  historyDialog.querySelector('.feedback-history-list').addEventListener('click',event=>{const trigger=event.target.closest('[data-history-entry]');if(!trigger)return;trigger.nextElementSibling.classList.toggle('is-hidden');trigger.classList.toggle('expanded');});
  historyDialog.querySelector('.dialog-close').addEventListener('click',()=>historyDialog.close());
})();
