(() => {
  const page=document.querySelector('#summaryPage');
  const rows=[
    {id:'us',shop:'US Fashion Store',country:'美国',warehouses:['跨境仓'],gmv:52468.8,orders:982,product:23911.6,shipping:8340.5,platform:3912.9,refund:1549.8,cost:36187.18,profit:16281.62,margin:31.03,refundRate:2.95,complete:'正常'},
    {id:'ph',shop:'PH Lifestyle Store',country:'菲律宾',warehouses:['菲律宾本土'],gmv:20142.18,orders:411,product:9820.6,shipping:3407.2,platform:1675.1,refund:975.4,cost:14270.03,profit:5872.15,margin:29.15,refundRate:4.84,complete:'部分缺失'},
    {id:'id',shop:'ID Trend Store',country:'印尼',warehouses:['印尼本土','跨境仓'],gmv:18234.6,orders:356,product:8661.1,shipping:3104.7,platform:1442.4,refund:742.1,cost:13910.3,profit:4324.3,margin:23.71,refundRate:4.07,complete:'部分缺失'},
    {id:'vn',shop:'VN Home Store',country:'越南',warehouses:['越南亚达','越南904千易'],gmv:16189.3,orders:318,product:8150.2,shipping:3052.1,platform:1260.8,refund:976.4,cost:14286.2,profit:1903.1,margin:11.76,refundRate:6.03,complete:'不可计算'},
    {id:'th',shop:'TH Market Store',country:'泰国',warehouses:['泰国本土'],gmv:21605.4,orders:419,product:11521.9,shipping:2366.8,platform:1665.2,refund:701.4,cost:15984.8,profit:5620.6,margin:26.01,refundRate:3.25,complete:'正常'}
  ];
  const $=id=>document.querySelector(id), fmt=(n,c='USD')=>c==='CNY'?`¥${(n*7.1842).toLocaleString('zh-CN',{maximumFractionDigits:2})}`:`$${n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  function visible(){const shop=$('#summaryShopFilter').value,country=$('#summaryCountryFilter').value,warehouse=$('#summaryWarehouseFilter').value;return rows.filter(r=>(!shop||r.shop===shop)&&(!country||r.country===country)&&(!warehouse||r.warehouses.includes(warehouse)));}
  function classFor(s){return s==='正常'?'':s==='部分缺失'?'partial':'none'}
  function render(){const list=visible(),currency=$('#summaryCurrencyFilter').value,total=list.reduce((a,r)=>({gmv:a.gmv+r.gmv,orders:a.orders+r.orders,cost:a.cost+r.cost,profit:a.profit+r.profit,refund:a.refund+r.refund}),{gmv:0,orders:0,cost:0,profit:0,refund:0}),margin=total.gmv?total.profit/total.gmv*100:0,refundRate=total.gmv?total.refund/total.gmv*100:0;$('#summaryGmv').textContent=fmt(total.gmv,currency);$('#summaryOrders').textContent=total.orders.toLocaleString();$('#summaryCosts').textContent=fmt(total.cost,currency);$('#summaryProfit').textContent=fmt(total.profit,currency);$('#summaryMargin').textContent=`净利率 ${margin.toFixed(2)}%`;$('#summaryRefund').textContent=`${refundRate.toFixed(2)}%`;$('#summaryScope').textContent=`统计范围：${list.length===1?list[0].shop:'全部已授权店铺'} · ${$('#summaryDateFilter').value} · ${currency}`;const key=$('#summarySort').value,sorters={profit:(a,b)=>b.profit-a.profit,gmv:(a,b)=>b.gmv-a.gmv,margin:(a,b)=>b.margin-a.margin,loss:(a,b)=>a.profit-b.profit,refund:(a,b)=>b.refundRate-a.refundRate};const sorted=[...list].sort(sorters[key]);$('#summaryStoresBody').innerHTML=sorted.map(r=>`<tr><td>${r.shop}</td><td>${fmt(r.gmv,currency)}</td><td>${fmt(r.cost,currency)}</td><td class="${r.profit>=0?'positive':''}">${fmt(r.profit,currency)}</td><td>${r.margin.toFixed(2)}%</td><td><span class="completion ${classFor(r.complete)}">${r.complete}</span></td><td><button class="detail-button" data-profit="${r.id}">详情</button></td></tr>`).join('')||'<tr><td colspan="7">没有符合筛选条件的利润数据</td></tr>';$('#summaryDetailBody').innerHTML=sorted.map(r=>`<tr><td>${r.shop}</td><td>${fmt(r.gmv,currency)}</td><td>${r.orders}</td><td>${fmt(r.product,currency)}</td><td>${fmt(r.shipping,currency)}</td><td>${fmt(r.platform,currency)}</td><td>${fmt(r.refund,currency)}</td><td>${fmt(r.cost,currency)}</td><td class="${r.profit>=0?'positive':''}">${fmt(r.profit,currency)}</td><td>${r.margin.toFixed(2)}%</td><td><span class="completion ${classFor(r.complete)}">${r.complete}</span></td><td><button class="detail-button" data-profit="${r.id}">详情</button></td></tr>`).join('')||'<tr><td colspan="12">没有符合筛选条件的利润数据</td></tr>';$('#summaryAlerts').innerHTML=list.filter(r=>r.complete!=='正常').map(r=>`<a href="#"><span class="alert-icon ${r.complete==='不可计算'?'':'warn'}">!</span><div><b>${r.shop}：${r.complete==='不可计算'?'关键成本数据缺失':'利润数据部分缺失'}</b><p>${r.complete==='不可计算'?'请等待管理员补齐成本与同步数据':'部分 SKU 成本或订单数据待补充'}</p></div></a>`).join('')||'<p class="summary-empty">当前统计范围内暂无异常提醒</p>';}
  function show(){['#dashboard','#currencyPage','#productsPage','#shippingPage','#ordersPage','#storesPage'].forEach(id=>$(id)?.classList.add('is-hidden'));page.classList.remove('is-hidden');$('#topbarTitle').textContent='利润汇总';$('#reportCurrency').classList.add('is-hidden');$('#topbarSubtitle').textContent='默认按店铺查看经营表现与利润数据完整度';$('#topbarSubtitle').classList.remove('is-hidden');document.querySelectorAll('.profit-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#summary'));render();}
  document.addEventListener('sales:navigate', event=>{if(event.detail?.route==='#summary')show();});$('#summarySearch')?.addEventListener('click',render);$('#summarySort')?.addEventListener('change',render);$('#summaryReset')?.addEventListener('click',()=>{['#summaryShopFilter','#summaryCountryFilter','#summaryWarehouseFilter'].forEach(id=>$(id).value='');$('#summaryDateFilter').value='近 30 天';$('#summaryCurrencyFilter').value='USD';$('#summarySort').value='profit';render();});
  const dialog=$('#profitDetailDialog');document.addEventListener('click',e=>{const id=e.target.dataset.profit;if(!id)return;const r=rows.find(item=>item.id===id),c=$('#summaryCurrencyFilter').value;$('#profitDetailContent').innerHTML=`<h2>${r.shop} · 利润明细</h2><p>${r.country} · 按店铺汇总 · 近 30 天</p><div class="profit-detail-grid">${[['销售额',fmt(r.gmv,c)],['有效订单数',r.orders],['商品成本',fmt(r.product,c)],['物流与代发成本',fmt(r.shipping,c)],['平台与支付费用',fmt(r.platform,c)],['退款金额',fmt(r.refund,c)],['总成本',fmt(r.cost,c)],['净利润',fmt(r.profit,c)],['净利率',r.margin.toFixed(2)+'%'],['结算汇率版本',r.country==='美国'?'USD/CNY · 2026-09':'本币/CNY · 2026-09'],['数据完整度',r.complete],['数据来源','订单、结算单、商品与仓库成本']].map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div>${r.complete==='正常'?'':`<div class="profit-detail-note">该店铺存在数据缺失。利润仅供参考，管理员补齐相关成本或订单数据后将自动更新。</div>`}`;dialog.showModal();});$('#closeProfitDetail')?.addEventListener('click',()=>dialog.close());render();
})();
